### ISSUE TITLE
Getting error 0XC000007B on win 8.1

### ISSUE THREAD

**Issue by cooltaby** [bbscoin/bbscoin-wallet#1]
Unable to launch wallet

**Comment by msxcms** [comment]
It's OK on win10
I will check it after installing win8.1 on a vmware

**Comment by msxcms** [comment]
https://imgur.com/a/nFLQy

As you can see, I can run the wallet correctly on a new installed Win 8.1 x64 after installing https://aka.ms/vs/15/release/vc_redist.x64.exe

Please check you system or provide me with more information. If you extract the program to a short name folder?

**Comment by cooltaby** [comment]
i have reinstalled vc_redist.x64 but still same issue. i have extracted files in D:\bit\wallet\bbscoinwallet_win_x64_v2.0. 
[DxDiag.txt](https://github.com/bbscoin/bbscoin-wallet/files/1700087/DxDiag.txt)

**Comment by randing89** [comment]
Installed Universal C Runtime solved the issue
