### ISSUE TITLE
not issue just info request

### ISSUE THREAD

**Issue by hongbaoblockchain** [bbscoin/bbscoin-wallet#2]
What is the dir to the file where you changed saving bbscoin wallet after closing gui?
Thanks

**Comment by randing89** [comment]
In windows: %user_name%\AppData\Roaming\BBSCoin
In OSX/*nix: ~/.BBSCoin

**Comment by hongbaoblockchain** [comment]
not the saved file location. I mean in the source code. When you close the gui it says "saving bbscoin data" in the grey splash box. Where is that part located in source?
